### ISSUE TITLE
How do I get the stat files?

### ISSUE THREAD

**Issue by SaibotMagd** [sanderslab/magellanmapper#51]
Hi,

I can't find a way to create the stat files for the label-eroding & smoothing step on my data. I'm looking for the files created in the basic protocol (I don't know which step but I only did everything till protocol 5)
- ADMBA-E18pt5_smoothing.csv
- ADMBA-E18pt5_smoothing_raw.csv
- ADMBA-E18pt5_stats.csv

When I rerun the protocol 5 they won't be recreate.

I only get the markers.csv. So how can I get them?

**Comment by yoda-vid** [comment]
Hi @SaibotMagd, great question! Those files are output to the atlas folder when running atlas import with smoothing on, but they're not currently generating when running the watershed-based smoothing (`--register merge_atlas_segs`). I think this was just to save time, but I can definitely add the output for the smoothing metrics as well. I'll add a profile switch too so it's optional.

Thanks for pointing this out!

**Comment by yoda-vid** [comment]
I've added a branch/PR that outputs smoothing stats now during the eroding/smoothing step. Let me know if it works for you!

**Comment by SaibotMagd** [comment]
> I've added a branch/PR that outputs smoothing stats now during the eroding/smoothing step. Let me know if it works for you!

Thanks again! I think its best to print the stats as default.
Its working but I only get: "xx_smoothing.csv & xx_smoothing_raw.csv" but not the summary: "xx_stats.csv".

**Comment by yoda-vid** [comment]
Thanks for testing this! I've updated the PR to output the `_stats.csv` file as well. It includes the volume and overlap metrics but skips the lateral planes metrics since this step doesn't involve the lateral extension. Let me know how it works for you.

**Comment by SaibotMagd** [comment]
Its not working:
Log:

` Aggregated smoothing metrics, weighted by original volume
root - INFO -  Filter_size  Compaction  Displacement  Smoothing_quality   Compactness  Compactness_SD  Compactness_CV  SA_to_vol  SA_to_vol_frac  Label_loss
         3.0    0.724976       0.26761           0.457366  11559.007301      9557.15278        0.826814   8.377889          0.6296         0.0
root - INFO - 
Labels lost from smoothing:
root - INFO - number of labels changed from 636 to 636
root - INFO - IDs of labels lost: []
root - INFO - 
Measuring overlap of labels:
root - INFO - Mean label-by-label DSC: 0.680738000849566
root - INFO - 
Volume ratio (smoothed:orig) weighted by orig size: 0.987561778416143
root - INFO - 
root - INFO - exported volume data per sample to CSV file: "/home/tgottsch/Atlas_project/magellanmapper/examples/fullStack/cpl_smoothing_raw.csv"
root - INFO - exported volume data per sample to CSV file: "/home/tgottsch/Atlas_project/magellanmapper/examples/fullStack/cpl_smoothing.csv"
root - INFO - cropping to original labels' extent with filter size of 1
root - INFO - 
Measuring overlap of atlas and combined watershed labels:
root - INFO - DSC of thresholded fixed image compared with combined labels:
root - INFO - Measuring overlap with thresholds of -20872.79099816573 (img1) and 1 (img2)
root - INFO - Adjusting spacing from (0.260504812002182, 0.26009052991867065, 0.03937007859349251) to (1.0, 1.0, 1.0), origin from (0.0, 0.0, 0.0) to (0.0, 0.0, 0.0), direction from (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0) to (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)
root - CRITICAL - Unhandled exception. Additional log saved to: /tmp/magellanmapper_error_ix59s2re.log
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/atlas/edge_seg.py", line 359, in edge_aware_segmentation
    atlas_refiner.measure_overlap_combined_labels(atlas_sitk, labels_sitk_seg)
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/atlas/atlas_refiner.py", line 1673, in measure_overlap_combined_labels
    return_masks=return_masks)
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/atlas/atlas_refiner.py", line 1593, in measure_overlap
    overlap_filter.Execute(binary_img1, binary_img2)
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/site-packages/SimpleITK/SimpleITK.py", line 43887, in Execute
    return _SimpleITK.LabelOverlapMeasuresImageFilter_Execute(self, image1, image2)
RuntimeError: Exception thrown in SimpleITK LabelOverlapMeasuresImageFilter_Execute: /mnt/e/src/build_se/ITK-prefix/include/ITK-4.13/itkImageToImageFilter.hxx:241:
itk::ERROR: LabelOverlapMeasuresImageFilter(0x55e980a99240): Inputs do not occupy the same physical space! 
InputImage Spacing: [1.0000000e+00, 1.0000000e+00, 1.0000000e+00], InputImage_1 Spacing: [2.6050481e-01, 2.6009053e-01, 3.9370079e-02]
	Tolerance: 1.0000000e-06

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tgottsch/Atlas_project/magellanmapper/run.py", line 237, in <module>
    main()
  File "/home/tgottsch/Atlas_project/magellanmapper/run.py", line 170, in main
    launch_magmap()
  File "/home/tgottsch/Atlas_project/magellanmapper/run.py", line 126, in launch_magmap
    cli.main()
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/io/cli.py", line 872, in main
    process_tasks()
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/io/cli.py", line 724, in process_tasks
    register.main()
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/atlas/register.py", line 1971, in main
    suffix=config.suffix)
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/atlas/edge_seg.py", line 449, in merge_atlas_segmentations
    path = result.get()
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
RuntimeError: Exception thrown in SimpleITK LabelOverlapMeasuresImageFilter_Execute: /mnt/e/src/build_se/ITK-prefix/include/ITK-4.13/itkImageToImageFilter.hxx:241:
itk::ERROR: LabelOverlapMeasuresImageFilter(0x55e980a99240): Inputs do not occupy the same physical space! 
InputImage Spacing: [1.0000000e+00, 1.0000000e+00, 1.0000000e+00], InputImage_1 Spacing: [2.6050481e-01, 2.6009053e-01, 3.9370079e-02]
	Tolerance: 1.0000000e-06 `

**Comment by SaibotMagd** [comment]
This isn't working:

```
Unhandled exception. Additional log saved to: /tmp/magellanmapper_error_5_q0db4w.log
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/atlas/edge_seg.py", line 359, in edge_aware_segmentation
    atlas_refiner.measure_overlap_combined_labels(atlas_sitk, labels_sitk_seg)
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/atlas/atlas_refiner.py", line 1673, in measure_overlap_combined_labels
    return_masks=return_masks)
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/atlas/atlas_refiner.py", line 1593, in measure_overlap
    overlap_filter.Execute(binary_img1, binary_img2)
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/site-packages/SimpleITK/SimpleITK.py", line 43887, in Execute
    return _SimpleITK.LabelOverlapMeasuresImageFilter_Execute(self, image1, image2)
RuntimeError: Exception thrown in SimpleITK LabelOverlapMeasuresImageFilter_Execute: /mnt/e/src/build_se/ITK/Modules/Core/Common/src/itkDataObject.cxx:393:
Requested region is (at least partially) outside the largest possible region.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tgottsch/Atlas_project/magellanmapper/run.py", line 237, in <module>
    main()
  File "/home/tgottsch/Atlas_project/magellanmapper/run.py", line 170, in main
    launch_magmap()
  File "/home/tgottsch/Atlas_project/magellanmapper/run.py", line 126, in launch_magmap
    cli.main()
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/io/cli.py", line 872, in main
    process_tasks()
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/io/cli.py", line 724, in process_tasks
    register.main()
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/atlas/register.py", line 1971, in main
    suffix=config.suffix)
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/atlas/edge_seg.py", line 449, in merge_atlas_segmentations
    path = result.get()
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
RuntimeError: Exception thrown in SimpleITK LabelOverlapMeasuresImageFilter_Execute: /mnt/e/src/build_se/ITK/Modules/Core/Common/src/itkDataObject.cxx:393:
Requested region is (at least partially) outside the largest possible region.
```

**Comment by yoda-vid** [comment]
Thanks for testing and the stack trace. Hm, haven't seen this one before and curious that it works in one orientation but not the other. Are you running this on 2D planes? Do you have any sample files I could try to reproduce this error?

I pushed an update that fixes another issue with `LabelOverlapMeasuresImageFilter` (#52). It looks different than the issue here but could possibly have fixed it too.

**Comment by SaibotMagd** [comment]
I think the mistake was on my side. It seems like it is impossible to do the "make_edge_images" step using images from different directions after another without deleting the files created before. 

Now it's working. Now i have to try to understand the meaning of the statistics. So #45 is now becoming more and more pressing.

**Comment by yoda-vid** [comment]
> I think the mistake was on my side. It seems like it is impossible to do the "make_edge_images" step using images from different directions after another without deleting the files created before.

Sounds good, no problem. Yes, the `make_edge_images` step does need to be rerun before running the `merge_atlas_segs` step if the original images are changed. Is this what you were encountering? `make_edge_images` shouldn't require manually deleting files ahead of time, but if so let me know.

> Because it seems like the coronal segmentation is to good. I don't think it makes sense to refine it because I don't see enough room for improvement. So all comes to the horizontal refinement step. What if I could get the DSC statistics for the coronal slices without doing the refinement to compare it with the refinement result from the horizontal view? Could it been used as a measure of quality between the point of views?

I agree that the coronal segmentations look quite smooth as-is. I may still be a bit confused about your exact setup, trying to understand why the horizontal vs coronal refinements give different outputs since the refinement (and DSC) works in 3D and should give the same output whether the input is given coronally or horizontally (though I have mainly tested atlases given in one orientation). Or are you doing successive 2D plane refinements on either 2D coronal or 2D horizontal planes rather than inputting a single 3D volume?

The DSC could be a way to compare the atlas outputs. The DSC output saved in the file just compares the foreground of the intensity image and aggregate labels, while the command-line output also shows the DSC of the original to refined labels to show how much the refinement has changed the labels (though not necessarily the quality of those changes). If you want to measure the quality of the refinement compared with histological boundaries, you could use the `--register vol_stats` tasks for metrics such as the intensity variation within each label to see if variation decreases with refinement (each label is more homogeneous) and distances to the histological edges.

```
./run.py <path-to-img> --register vol_stats --labels <path-to-labels>
```

**Comment by yoda-vid** [comment]
I posted a PR (#57) that fixes the atlas-to-labels DSC to use the new rather than the original labels image and also saves the label-to-labels DSC rather than just printing them to console.

**Comment by SaibotMagd** [comment]
> The DSC could be a way to compare the atlas outputs. The DSC output saved in the file just compares the foreground of the intensity image and aggregate labels, while the command-line output also shows the DSC of the original to refined labels to show how much the refinement has changed the labels (though not necessarily the quality of those changes). If you want to measure the quality of the refinement compared with histological boundaries, you could use the `--register vol_stats` tasks for metrics such as the intensity variation within each label to see if variation decreases with refinement (each label is more homogeneous) and distances to the histological edges.
> 
> ```
> ./run.py <path-to-img> --register vol_stats --labels <path-to-labels>
> ```

This seems not to work for me: 
`
magmap.io.cli - INFO - Launched MagellanMapper from /home/toolboxes/magellanmapper/run.py
root - INFO - Set filenames to ['/home/toolboxes/magellanmapper/examples/fullres/fullres_atlasVolume.nii'], current filename /home/toolboxes/magellanmapper/examples/fullres/fullres_atlasVolume.nii
root - INFO - Set default (channel 0) ROI profile: default
root - INFO - Set atlas profile to default
root - INFO - Set labels to {<AtlasLabels.PATH_REF: 1>: '/home/toolboxes/magellanmapper/examples/fullres/fullres_annotation.nii', <AtlasLabels.LEVEL: 2>: None, <AtlasLabels.ID: 3>: None, <AtlasLabels.ORIG_COLORS: 4>: 1, <AtlasLabels.SYMMETRIC_COLORS: 5>: True, <AtlasLabels.BINARY: 6>: None, <AtlasLabels.TRANSLATE_LABELS: 7>: None, <AtlasLabels.TRANSLATE_CHILDREN: 8>: None}
root - INFO - Set register type to vol_stats
root - INFO - setting up Matplotlib style default
root - INFO - applying theme DEFAULT
root - INFO - Loaded database from /home/.local/share/MagellanMapper/magmap.db
root - INFO - set multiprocessing start method to fork
root - INFO - Performing register task: RegisterTypes.VOL_STATS
magmap.atlas.ontology - ERROR - Error tokenizing data. C error: Expected 1 fields in line 320762, saw 6136
Traceback (most recent call last):
  File "/home/toolboxes/magellanmapper/magmap/atlas/ontology.py", line 53, in load_labels_ref
    labels_ref = pd.read_csv(path)
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 320762, saw 6136

root - CRITICAL - Unhandled exception. Additional log saved to: /tmp/magellanmapper_error_xyb2skpe.log
Traceback (most recent call last):
  File "/home/toolboxes/magellanmapper/magmap/atlas/ontology.py", line 53, in load_labels_ref
    labels_ref = pd.read_csv(path)
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 320762, saw 6136


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/toolboxes/magellanmapper/run.py", line 237, in <module>
    main()
  File "/home/toolboxes/magellanmapper/run.py", line 170, in main
    launch_magmap()
  File "/home/toolboxes/magellanmapper/run.py", line 126, in launch_magmap
    cli.main()
  File "/home/toolboxes/magellanmapper/magmap/io/cli.py", line 872, in main
    process_tasks()
  File "/home/toolboxes/magellanmapper/magmap/io/cli.py", line 724, in process_tasks
    register.main()
  File "/home/toolboxes/magellanmapper/magmap/atlas/register.py", line 1996, in main
    extra_metrics=extra_metric_groups)
  File "/home/toolboxes/magellanmapper/magmap/atlas/register.py", line 1322, in volumes_by_id
    ontology.load_labels_ref(labels_ref_path))
  File "/home/toolboxes/magellanmapper/magmap/atlas/ontology.py", line 57, in load_labels_ref
    f"Could not load labels reference file from '{path}', skipping")
FileNotFoundError: Could not load labels reference file from '/home/toolboxes/magellanmapper/examples/fullres/fullres_annotation.nii', skipping
Starting MagellanMapper run script...
Out[7]: 256
`

**Comment by SaibotMagd** [comment]
Update:
What do you mean by: "--labels "? I tried it with the example data using "ontology17.json" as the labels file and it worked. So do I need such a json file?

**Comment by yoda-vid** [comment]
> I'm curious: What's the difference between the "--img $folder" parameter and the imagecall without the "--img" flag: "run.py atlasVolume.nii"?

I made `--img` optional in v1.4 as a convenience when the image path is the first argument since it's used with most commands. Keeping `--img` still works and also lets you put it elsewhere in the command (eg `./run.py --register vol_stats --img <path-to-img> --labels <path-to-labels>`, where the image path isn't the first argument).

> What do you mean by: "--labels "? I tried it with the example data using "ontology17.json" as the labels file and it worked. So do I need such a json file?

Glad it works now! The `--labels` parameter is for the labels reference/ontology file, eg the `ontology17.json` file that you used, which is needed to get the labels and their hierarchy. The labels/annotation image file path doesn't need to be specified here since it's found automatically based on the main image name, assuming it's been registered to the main image.

I just posted a PR (#61) so that you can use a flat CSV file like the `region_ids.csv` file in the sample data instead of a JSON file. The CSV can even have just a single column, `Regions`, with the IDs of each of the labels to measure. Let me know how it works for you.

I've also been working on a document for all the command line flags to summarize them and hopefully make things easier. It's a work in progress so let me know if you have any suggestions for it (and feel free to edit/PR)!

https://github.com/sanderslab/magellanmapper/blob/master/docs/cli.md

**Comment by SaibotMagd** [comment]
> Glad it works now! The `--labels` parameter is for the labels reference/ontology file, eg the `ontology17.json` file that you used, which is needed to get the labels and their hierarchy. The labels/annotation image file path doesn't need to be specified here since it's found automatically based on the main image name, assuming it's been registered to the main image.

What does it mean "it's been registered"? Yes I registered the annotations to my ls-image, but I never did this with magellan only external.

> I just posted a PR (#61) so that you can use a flat CSV file like the `region_ids.csv` file in the sample data instead of a JSON file. The CSV can even have just a single column, `Regions`, with the IDs of each of the labels to measure. Let me know how it works for you.

I tried this but it isn't working, at least for a 2D image. I create a csv file only consisting of the regions in this particular image (np.unique). I also tried to copy the other columns from the regions_ids.csv, so it looks like:
![grafik](https://user-images.githubusercontent.com/67700096/124585141-4e2b9e80-de55-11eb-8a83-b2edfceb7239.png)

This is the error log:

```
magmap.io.cli - INFO - Launched MagellanMapper from /home/toolboxes/magellanmapper/run.py
root - INFO - Set filenames to ['/home/toolboxes/magellanmapper/examples/singleSlice'], current filename /home/toolboxes/magellanmapper/examples/singleSlice
root - INFO - Set default (channel 0) ROI profile: default
root - INFO - Set atlas profile to default
root - INFO - Set labels to {<AtlasLabels.PATH_REF: 1>: '/home/toolboxes/magellanmapper/examples/singleSlice/region_ids.csv', <AtlasLabels.LEVEL: 2>: None, <AtlasLabels.ID: 3>: None, <AtlasLabels.ORIG_COLORS: 4>: 1, <AtlasLabels.SYMMETRIC_COLORS: 5>: True, <AtlasLabels.BINARY: 6>: None, <AtlasLabels.TRANSLATE_LABELS: 7>: None, <AtlasLabels.TRANSLATE_CHILDREN: 8>: None}
root - INFO - Set register type to vol_stats
root - INFO - setting up Matplotlib style default
root - INFO - applying theme DEFAULT
root - INFO - Loaded database from /home/.local/share/MagellanMapper/magmap.db
root - INFO - set multiprocessing start method to fork
root - INFO - Performing register task: RegisterTypes.VOL_STATS
root - CRITICAL - Unhandled exception. Additional log saved to: /tmp/magellanmapper_error_cskzah_z.log
Traceback (most recent call last):
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'msg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/toolboxes/magellanmapper/run.py", line 237, in <module>
    main()
  File "/home/toolboxes/magellanmapper/run.py", line 170, in main
    launch_magmap()
  File "/home/toolboxes/magellanmapper/run.py", line 126, in launch_magmap
    cli.main()
  File "/home/toolboxes/magellanmapper/magmap/io/cli.py", line 872, in main
    process_tasks()
  File "/home/toolboxes/magellanmapper/magmap/io/cli.py", line 724, in process_tasks
    register.main()
  File "/home/toolboxes/magellanmapper/magmap/atlas/register.py", line 1996, in main
    extra_metrics=extra_metric_groups)
  File "/home/toolboxes/magellanmapper/magmap/atlas/register.py", line 1322, in volumes_by_id
    ontology.load_labels_ref(labels_ref_path))
  File "/home/toolboxes/magellanmapper/magmap/atlas/ontology.py", line 122, in create_aba_reverse_lookup
    labels_ref["msg"][0], config.ABAKeys.ABA_ID.value,
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'msg'
Starting MagellanMapper run script...
Out[27]: 256
```

**Comment by yoda-vid** [comment]
> What does it mean "it's been registered"? Yes I registered the annotations to my ls-image, but I never did this with magellan only external.

The registration outputs paths to specific filenames, eg `_annotation.mhd` or `.nii.gz` at the end of labels images, and `vol_stats` just looks for those paths.

Is your folder structure like this?

```
/home/toolboxes/magellanmapper/examples/singleSlice:
atlasVolume.nii
annotation.nii
```

This should also work since I made a special case for files in the ABA convention. You can give the folder path as the img argument, and it should find the associated labels image file. The log output should also show where it's looking for files in case it doesn't find it, and you can move it there.

> I tried this but it isn't working, at least for a 2D image. I create a csv file only consisting of the regions in this particular image (np.unique). I also tried to copy the other columns from the regions_ids.csv, so it looks like

The CSV file looks good. Volume stats with the CSV version doesn't follow label hierarchies yet, so something I'll need to add. The error looks like what I got before. Did you try it on the PR's branch (`access_df_lookup`)? I haven't merged it in yet, so it's still just in that branch.

**Comment by SaibotMagd** [comment]
> The registration outputs paths to specific filenames, eg `_annotation.mhd` or `.nii.gz` at the end of labels images, and `vol_stats` just looks for those paths.

I'm sorry, I don't understand what that means.

> 
> Is your folder structure like this?
> 
> ```
> /home/toolboxes/magellanmapper/examples/singleSlice:
> atlasVolume.nii
> annotation.nii
> ```

Yes that's how it is. + region_ids.csv , just to be sure: the 3 columns on the right are "fakes", I just copied them from ADMBA-E18pt5/region_ids.csv and added my grey-values in the first column.

> 
> This should also work since I made a special case for files in the ABA convention. You can give the folder path as the img argument, and it should find the associated labels image file. The log output should also show where it's looking for files in case it doesn't find it, and you can move it there.

Yes the error message mention something about the ABA atlas template. But what does this have to do with the calculation of the intensity values? Could it be that he try to find an ID for a particular grey-value in the ABA atlas, because my atlasVolume doesn't share all of the grey-values from the ABA atlas because it isn't a regular mouse ;). So probably he can not find a label for a grey-value? 

> The CSV file looks good. Volume stats with the CSV version doesn't follow label hierarchies yet, so something I'll need to add. The error looks like what I got before. Did you try it on the PR's branch (`access_df_lookup`)? I haven't merged it in yet, so it's still just in that branch.

I'm totally new with all the git branch, pull request stuff, so I missed that. But now I tried it also using the new branch. 

So the error-log changed a little bit:

```
magmap.io.cli - INFO - Launched MagellanMapper from /home/toolboxes/magellanmapper/run.py
root - INFO - Set filenames to ['/home/toolboxes/magellanmapper/examples/singleSlice/'], current filename /home/toolboxes/magellanmapper/examples/singleSlice/
root - INFO - Set default (channel 0) ROI profile: default
root - INFO - Set atlas profile to default
root - INFO - Set labels to {<AtlasLabels.PATH_REF: 1>: '/home/toolboxes/magellanmapper/examples/singleSlice/region_ids.csv', <AtlasLabels.LEVEL: 2>: None, <AtlasLabels.ID: 3>: None, <AtlasLabels.ORIG_COLORS: 4>: 1, <AtlasLabels.SYMMETRIC_COLORS: 5>: True, <AtlasLabels.BINARY: 6>: None, <AtlasLabels.TRANSLATE_LABELS: 7>: None, <AtlasLabels.TRANSLATE_CHILDREN: 8>: None}
root - INFO - Set register type to vol_stats
root - INFO - setting up Matplotlib style default
root - INFO - applying theme DEFAULT
root - INFO - Loaded database from /home/.local/share/MagellanMapper/magmap.db
root - INFO - set multiprocessing start method to fork
root - INFO - Performing register task: RegisterTypes.VOL_STATS
root - CRITICAL - Unhandled exception. Additional log saved to: /tmp/magellanmapper_error_n44hbm0n.log
Traceback (most recent call last):
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'msg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/toolboxes/magellanmapper/run.py", line 237, in <module>
    main()
  File "/home/toolboxes/magellanmapper/run.py", line 170, in main
    launch_magmap()
  File "/home/toolboxes/magellanmapper/run.py", line 126, in launch_magmap
    cli.main()
  File "/home/toolboxes/magellanmapper/magmap/io/cli.py", line 872, in main
    process_tasks()
  File "/home/toolboxes/magellanmapper/magmap/io/cli.py", line 724, in process_tasks
    register.main()
  File "/home/toolboxes/magellanmapper/magmap/atlas/register.py", line 1996, in main
    extra_metrics=extra_metric_groups)
  File "/home/toolboxes/magellanmapper/magmap/atlas/register.py", line 1322, in volumes_by_id
    ontology.load_labels_ref(labels_ref_path))
  File "/home/toolboxes/magellanmapper/magmap/atlas/ontology.py", line 122, in create_aba_reverse_lookup
    labels_ref["msg"][0], config.ABAKeys.ABA_ID.value,
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'msg'
Starting MagellanMapper run script...
Out[53]: 256
```

**Comment by yoda-vid** [comment]
> I'm totally new with all the git branch, pull request stuff, so I missed that. But now I tried it also using the new branch.

No worries! Thanks for trying the new branch. The error still looks like the old one though. The error is showing that the file wasn't loaded because it's treating it as a JSON file, which the new branch updates to detect CSV files. If you do `git log`, does it show the commit, fa9aa37dfedfcfa2c66f2ce404a7f041920164c9 , from PR #61? Does `git fetch; git checkout access_df_lookup` bring in the new code?

> But what does this have to do with the calculation of the intensity values? Could it be that he try to find an ID for a particular grey-value in the ABA atlas, because my atlasVolume doesn't share all of the grey-values from the ABA atlas because it isn't a regular mouse ;).

By "grey-values," do you mean the label integer values in your annotations image? The region IDs column is used to list the label integer-defined regions to extract from the annotations/labels image (not the intensity image). Is that what you were referring to?

> I'm sorry, I don't understand what that means.

The "registered images" expects an atlas folder structure like this:
- "Base" path: `/home/me/my_image`
- Intensity/histology/"atlas" image: `/home/me/my_image_atlasVolume.nii.gz`
- Annotation/labels image: `/home/me/my_image_annotation.nii.gz`
- Other registered images, eg atlas edges: `/home/me/my_image_atlasEdge.nii.gz`
- Load intensity and annotations image: `./run.py --img /home/me/my_image --reg_suffixes atlasVolume.nii.gz annotation.nii.gz`

So the base path can be given as the `--img` argument, and all the registered images are found based on it, without having to give their full paths. The intention was to make things shorter and more convenient, though I realize it can be confusing (always open to suggestions!). I recently added support to give an absolute path for the registered images (eg `--reg_suffixes annotation=/home/me/my_image_atlasEdge.nii.gz`) in case it has a different base path. Does this clarify anything you referred to in #26?

Your folder structure is slightly different, where the base path is a folder, and `atlasVolume.nii.gz` and `annotation.nii.gz` are full filenames, similar to the ABA file structure. This is treated as a special case and should also find the related images.

**Comment by SaibotMagd** [comment]
Sorry for my late answer, I'm facing some very serious issues regarding other parts of my pipeline.

> > But what does this have to do with the calculation of the intensity values? Could it be that he try to find an ID for a particular grey-value in the ABA atlas, because my atlasVolume doesn't share all of the grey-values from the ABA atlas because it isn't a regular mouse ;).
> 
> By "grey-values," do you mean the label integer values in your annotations image? The region IDs column is used to list the label integer-defined regions to extract from the annotations/labels image (not the intensity image). Is that what you were referring to?

Refering to "atlasVolume" in my post before was a mistake. It should be "annotations". So every grey-value in the annotation file refer to one ID from the csv-label file. And there're 100% identical in each region. On the other hand in the "atlasVolume" File the grey-values in a particular region aren't homogenious and do not match the IDs from the label-file. So it was a spelling mistake.


I hope I can try this out this week, but I found a source explaining why I can't use neither the DSC nor intensity homogenious stats to optimize my results.

**Comment by yoda-vid** [comment]
Sounds good. I've merged in PR #61 so that it's on the main branch now. I've also opened #67 with additional updates to volume stats such as merging in the region names automatically and support for hierarchical labels loaded from CSV files, if that's relevant.

Feel free to suggest any other stats that might be worth measuring and integrating to optimize your results. Hope this helps.

**Comment by SaibotMagd** [comment]
After doing "--register vol_stats" on the ABA_25um_atlas I got this output:

```

        original    L         57        NaN           NaN         NaN           NaN            NaN           NaN           NaN            NaN               NaN       NaN           NaN           NaN            NaN
        original    L         65        NaN           NaN         NaN           NaN            NaN           NaN           NaN            NaN               NaN       NaN           NaN           NaN            NaN
        original    L        624        NaN           NaN         NaN           NaN            NaN           NaN           NaN            NaN               NaN       NaN           NaN           NaN            NaN
        original    L  304325711        NaN           NaN         NaN           NaN            NaN           NaN           NaN            NaN               NaN       NaN           NaN           NaN            NaN
root - INFO - Sample Condition  Side Region      Volume  Nuclei  Density  RegVolMean  RegNucMean  RegDensityMean  VarNuclei  VarIntensity   EdgeSize   EdgeDistSum  EdgeDistMean
        original  both    all  462.409828     NaN      NaN    4.585572         NaN             NaN        NaN   5059.815171  7060879.0  2.179814e+13     83.573098
root - INFO - time elapsed to measure variation: 57.54461669921875
root - INFO - Backed up /home/tgottsch/toolboxes/magellanmapper/examples/allen25um/_volumes.csv to /home/tgottsch/toolboxes/magellanmapper/examples/allen25um/_volumes(1).csv
root - INFO - exported volume data per sample to CSV file: "/home/tgottsch/toolboxes/magellanmapper/examples/allen25um/_volumes.csv"
root - INFO - Backed up vols_by_sample.csv to vols_by_sample(2).csv
root - INFO - exported volume data per sample to CSV file: "vols_by_sample.csv"
root - INFO - Backed up vols_by_sample_summary.csv to vols_by_sample_summary(2).csv
root - INFO - exported volume data per sample to CSV file: "vols_by_sample_summary.csv"
root - INFO - time elapsed for volumes by ID: 59.92438530921936
Starting MagellanMapper run script...
Out[39]: 0
```

"_volumes.csv" exists, but "vols_by_sample.csv" nor "vols_by_sample_summary.csv" can be found.

**Comment by SaibotMagd** [comment]
I tried to run '--vol_stats' on the E11pt5 and got this error:

```
magmap.io.cli - INFO - Launched MagellanMapper from /home/saibotMagd/toolboxes/magellanmapper/run.py
root - INFO - Set filenames to ['/home/saibotMagd/srcImageData/metricCalc/ADMBA-E11pt5_pub/3Drecon-ADMBA-E11pt5'], current filename /home/saibotMagd/srcImageData/metricCalc/ADMBA-E11pt5_pub/3Drecon-ADMBA-E11pt5
root - INFO - Set default (channel 0) ROI profile: default
root - INFO - Set atlas profile to default
root - INFO - Set labels to {<AtlasLabels.PATH_REF: 1>: '/home/saibotMagd/srcImageData/metricCalc/ADMBA-E11pt5_pub/3Drecon-ADMBA-E11pt5region_ids_ADMBA.csv', <AtlasLabels.LEVEL: 2>: None, <AtlasLabels.ID: 3>: None, <AtlasLabels.ORIG_COLORS: 4>: 1, <AtlasLabels.SYMMETRIC_COLORS: 5>: True, <AtlasLabels.BINARY: 6>: None, <AtlasLabels.TRANSLATE_LABELS: 7>: None, <AtlasLabels.TRANSLATE_CHILDREN: 8>: None}
root - INFO - Set register type to vol_stats
root - INFO - setting up Matplotlib style default
root - INFO - applying theme DEFAULT
root - INFO - Loaded database from /home/saibotMagd/.local/share/MagellanMapper/magmap.db
root - INFO - set multiprocessing start method to fork
root - INFO - Performing register task: RegisterTypes.VOL_STATS
root - CRITICAL - Unhandled exception. Additional log saved to: /tmp/magellanmapper_error_cyubic_o.log
Traceback (most recent call last):
  File "/home/saibotMagd/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'msg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/saibotMagd/toolboxes/magellanmapper/run.py", line 237, in <module>
    main()
  File "/home/saibotMagd/toolboxes/magellanmapper/run.py", line 170, in main
    launch_magmap()
  File "/home/saibotMagd/toolboxes/magellanmapper/run.py", line 126, in launch_magmap
    cli.main()
  File "/home/saibotMagd/toolboxes/magellanmapper/magmap/io/cli.py", line 872, in main
    process_tasks()
  File "/home/saibotMagd/toolboxes/magellanmapper/magmap/io/cli.py", line 724, in process_tasks
    register.main()
  File "/home/saibotMagd/toolboxes/magellanmapper/magmap/atlas/register.py", line 1996, in main
    extra_metrics=extra_metric_groups)
  File "/home/saibotMagd/toolboxes/magellanmapper/magmap/atlas/register.py", line 1322, in volumes_by_id
    ontology.load_labels_ref(labels_ref_path))
  File "/home/saibotMagd/toolboxes/magellanmapper/magmap/atlas/ontology.py", line 122, in create_aba_reverse_lookup
    labels_ref["msg"][0], config.ABAKeys.ABA_ID.value,
  File "/home/saibotMagd/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/saibotMagd/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'msg'
Starting MagellanMapper run script...
Out[132]: 256
```

**Comment by yoda-vid** [comment]
> I tried to run '--vol_stats' on the E11pt5-Dataset from https://search.kg.ebrains.eu/instances/Project/b8a8e2d3-4787-45f2-b010-589948c33f20 and got this error:
>
> ```
> magmap.io.cli - INFO - Launched MagellanMapper from /home/saibotMagd/toolboxes/magellanmapper/run.py
> root - INFO - Set filenames to ['/home/saibotMagd/srcImageData/metricCalc/ADMBA-E11pt5_pub/3Drecon-ADMBA-E11pt5'], current filename /home/saibotMagd/srcImageData/metricCalc/ADMBA-E11pt5_pub/3Drecon-ADMBA-E11pt5
> root - INFO - Set default (channel 0) ROI profile: default
> root - INFO - Set atlas profile to default
> root - INFO - Set labels to {<AtlasLabels.PATH_REF: 1>: '/home/saibotMagd/srcImageData/metricCalc/ADMBA-E11pt5_pub/3Drecon-ADMBA-E11pt5region_ids_ADMBA.csv', <AtlasLabels.LEVEL: 2>: None, <AtlasLabels.ID: 3>: None, <AtlasLabels.ORIG_COLORS: 4>: 1, <AtlasLabels.SYMMETRIC_COLORS: 5>: True, <AtlasLabels.BINARY: 6>: None, <AtlasLabels.TRANSLATE_LABELS: 7>: None, <AtlasLabels.TRANSLATE_CHILDREN: 8>: None}
> ```

I think this needs another slash in `3Drecon-ADMBA-E11pt5region_ids_ADMBA.csv` so that it's `3Drecon-ADMBA-E11pt5/region_ids_ADMBA.csv`? It's working otherwise for me but let me know if you still get an error.

> "_volumes.csv" exists, but neither "vols_by_sample.csv" nor "vols_by_sample_summary.csv" can be found.

The  "vols_by_sample.csv" and "vols_by_sample_summary.csv" files actually get output to the current working directory, whereas the "_volumes.csv" file is output to the atlas directory. "vols_by_sample.csv" and "_volumes.csv" are the same here, but "vols_by_sample.csv" includes all atlases when running vol_stats on multiple atlases at the same time. Do you see those files in the working directory?

Thanks and hope that helps!

**Comment by SaibotMagd** [comment]
I found the "vol_by_sample.csv" and "vols_bz_sample_summary.csv" in my home directory, so I think I messed up the "find file command". But either way the content of these files don't help at all. I still don't know the command to calculate the DSC and intensity metrics. So I called the "meas_dice" function right from atlas_stats.py on every label mask by hand, but the result is poor. Also tried to calculate the intensity values and weight them using the label-annotation sizes. Here're the results:

```
metricfile = /home/saibotMagd/srcImageData/metricCalc/ADMBA-E15pt5_pub/3Drecon-ADMBA-E15pt5_dsc-intensity_merged.csv, 
           mean-dsc = 1.0, 
           md-dsc = 1.0, 
           intensity_weightedStd = 0.1378186019605416
metricfile = /home/saibotMagd/srcImageData/metricCalc/ADMBA-E11pt5_pub/3Drecon-ADMBA-E11pt5_dsc-intensity_merged.csv, 
           mean-dsc = 1.0, 
           md-dsc = 1.0, 
           intensity_weightedStd = 0.17839092646983812
metricfile = /home/saibotMagd/srcImageData/metricCalc/ADMBA-E13pt5_pub/3Drecon-ADMBA-E13pt5_dsc-intensity_merged.csv, 
           mean-dsc = 1.0, 
           md-dsc = 1.0, 
           intensity_weightedStd = 0.16464195356717792
metricfile = /home/saibotMagd/srcImageData/metricCalc/ADMBA-P28_pub/3Drecon-ADMBA-P28_dsc-intensity_merged.csv, 
           mean-dsc = 1.0, 
           md-dsc = 1.0, 
           intensity_weightedStd = 0.10361837119587528
metricfile = /home/saibotMagd/srcImageData/metricCalc/ADMBA-P56_pub/3Drecon-ADMBA-P56_dsc-intensity_merged.csv, 
           mean-dsc = 0.9983491882375757, 
           md-dsc = 1.0, 
           intensity_weightedStd = 0.10134510718620612
metricfile = /home/saibotMagd/srcImageData/metricCalc/ADMBA-P4_pub/3Drecon-ADMBA-P4_dsc-intensity_merged.csv, 
           mean-dsc = 1.0, 
           md-dsc = 1.0, 
           intensity_weightedStd = 0.15182643848396013
metricfile = /home/saibotMagd/srcImageData/metricCalc/aba_25um/aba_25um_dsc-intensity_merged.csv, 
           mean-dsc = 0.9256435958281721, 
           md-dsc = 1.0, 
           intensity_weightedStd = 0.1401675900369678
metricfile = /home/saibotMagd/srcImageData/metricCalc/ADMBA-P14_pub/3Drecon-ADMBA-P14_dsc-intensity_merged.csv, 
           mean-dsc = 0.9999899617951389, 
           md-dsc = 1.0, 
           intensity_weightedStd = 0.13145686413093083
metricfile = /home/saibotMagd/srcImageData/metricCalc/ADMBA-E18pt5_pub/3Drecon-ADMBA-E18pt5_dsc-intensity_merged.csv, 
           mean-dsc = 1.0, 
           md-dsc = 1.0, 
           intensity_weightedStd = 0.1782986529378437
```


I renamed the region_id file again but it isn't working:

```
bash = run + \
        ' --img ' + '/home/saibotMagd/srcImageData/metricCalc/ADMBA-E11pt5_pub/3Drecon-ADMBA-E11pt5' + \
        " --register vol_stats " + \
        ' --labels ' + '/home/saibotMagd/srcImageData/metricCalc/ADMBA-E11pt5_pub/region_ids_ADMBA.csv'
os.system(bash)
magmap.io.cli - INFO - Launched MagellanMapper from /home/saibotMagd/toolboxes/magellanmapper/run.py
root - INFO - Set filenames to ['/home/saibotMagd/srcImageData/metricCalc/ADMBA-E11pt5_pub/3Drecon-ADMBA-E11pt5'], current filename /home/saibotMagd/srcImageData/metricCalc/ADMBA-E11pt5_pub/3Drecon-ADMBA-E11pt5
root - INFO - Set default (channel 0) ROI profile: default
root - INFO - Set atlas profile to default
root - INFO - Set labels to {<AtlasLabels.PATH_REF: 1>: '/home/saibotMagd/srcImageData/metricCalc/ADMBA-E11pt5_pub/region_ids_ADMBA.csv', <AtlasLabels.LEVEL: 2>: None, <AtlasLabels.ID: 3>: None, <AtlasLabels.ORIG_COLORS: 4>: 1, <AtlasLabels.SYMMETRIC_COLORS: 5>: True, <AtlasLabels.BINARY: 6>: None, <AtlasLabels.TRANSLATE_LABELS: 7>: None, <AtlasLabels.TRANSLATE_CHILDREN: 8>: None}
root - INFO - Set register type to vol_stats
root - INFO - setting up Matplotlib style default
root - INFO - applying theme DEFAULT
root - INFO - Loaded database from /home/saibotMagd/.local/share/MagellanMapper/magmap.db
root - INFO - set multiprocessing start method to fork
root - INFO - Performing register task: RegisterTypes.VOL_STATS
root - CRITICAL - Unhandled exception. Additional log saved to: /tmp/magellanmapper_error_yjvj9_1m.log
Traceback (most recent call last):
  File "/home/saibotMagd/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'msg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/saibotMagd/toolboxes/magellanmapper/run.py", line 237, in <module>
    main()
  File "/home/saibotMagd/toolboxes/magellanmapper/run.py", line 170, in main
    launch_magmap()
  File "/home/saibotMagd/toolboxes/magellanmapper/run.py", line 126, in launch_magmap
    cli.main()
  File "/home/saibotMagd/toolboxes/magellanmapper/magmap/io/cli.py", line 872, in main
    process_tasks()
  File "/home/saibotMagd/toolboxes/magellanmapper/magmap/io/cli.py", line 724, in process_tasks
    register.main()
  File "/home/saibotMagd/toolboxes/magellanmapper/magmap/atlas/register.py", line 1996, in main
    extra_metrics=extra_metric_groups)
  File "/home/saibotMagd/toolboxes/magellanmapper/magmap/atlas/register.py", line 1322, in volumes_by_id
    ontology.load_labels_ref(labels_ref_path))
  File "/home/saibotMagd/toolboxes/magellanmapper/magmap/atlas/ontology.py", line 122, in create_aba_reverse_lookup
    labels_ref["msg"][0], config.ABAKeys.ABA_ID.value,
  File "/home/saibotMagd/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/saibotMagd/anaconda3/envs/mag/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'msg'
Starting MagellanMapper run script...
```

**Comment by SaibotMagd** [comment]
This is how I called the meas_dice function:

```
annoImg[annoImg == label] = 1  
    annoImg[annoImg != 1] = 0  
    atlasVol = annoImg * atlasVol
    atlasVol[atlasVol > 0] = 1
    annoCount = np.count_nonzero(annoImg)
    volCount = np.count_nonzero(atlasVol)
    dsc_full = meas_dice(atlasVol, annoImg)
```

I think the problem comes from the "binarization" step: "    atlasVol[atlasVol > 0] = 1". It would be great if there were a better way to do this, but the command line calls are so complex, I still don't know how to get it working.

Here's an example:
![image](https://user-images.githubusercontent.com/67700096/132365404-21074fee-2df4-4c6e-b7be-763cf62d16d3.png)
this is region ID is 1104 (V3) and the DSC from my call is 0.266. As you can see the overlap is poor.

**Comment by yoda-vid** [comment]
> I renamed the region_id file again but it isn't working

This reminds of the error fixed in #61, now updated on the main branch, so maybe that will fix it?

> But the results are to bad to use them.

I'm sorry that the stats aren't working out for you. Perhaps we can discuss this more to see what results you're getting and how to troubleshoot.

**Comment by SaibotMagd** [comment]
I did it! To make this possible I had to run the whole pipeline, and throw away the results I don't need:

1. run make_edges 
2. overwrite the annotationEdge.mhd/raw with my gradient Edge detection result
3. run merge_atlas
4. optional: delete or overwrite the annotation.mhd/raw if you don't need the smoothing results
5. run vol_stats using --labels region_ids.csv 
6. find the vols_by_sample.csv and vols_by_sample_summary.csv and move them to the working directory

This is the result and it seems great:
![image](https://user-images.githubusercontent.com/67700096/142627812-de2c8b93-61d8-400e-92cb-c596893e25dd.png)
as you can see the magellanmapper results (left) are identical to the statistics from itk-snap (right).

I thought VarIntensity would be the variance but it stands for "variation".

**Comment by yoda-vid** [comment]
Excellent! Glad it worked out, and thanks for reporting your steps on how to make this work. I'll definitely need to add this into the docs.

Thanks for all your help with this!
